version: '3.9'
services:
  frontend:
    build:
      context: .
      target: nginx
    image: frontend:latest
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/web

networks:
  default:
    name: api
    external: true
