version: '3.9'
services:
  frontend:
    build:
      context: .
      target: nginx
    image: frontend:latest
    ports:
      - 80:80
    volumes:
      - ./dist:/var/www/web
      - ./src/assets/static:/var/www/web/static

networks:
  default:
    name: api
    external: true
