version: '3.9'
services:
  frontend:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dist:/var/www/web:ro
      - ./src/assets/static:/var/www/web/static:ro
      - ./nginx/conf/:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot:rw
      - ./certbot/conf/:/etc/letsencrypt:rw

networks:
  default:
    name: api
    external: true
