version: '3.9'
services:
  frontend:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./dist:/var/www/web/
      - ./src/assets/static:/var/www/web/static/
      - ./nginx/conf/:/etc/nginx/conf.d/
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf/:/etc/nginx/ssl/

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/

networks:
  default:
    name: api
    external: true
