version: '3.9'
services:
  app:
    build:
      context: .
      target: nginx
    image: cj-frontend:latest
    networks:
      - backend
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/web

networks:
  backend:
    name: cj-backend
    external: true
